### ISSUE TITLE
fingerprint generation: Input structure could not be split into protein and ligand.

### ISSUE THREAD

**Issue by poojari1** [skalyaanamoorthy/PoseFilter#1]
Hi, 

I am able to run RMS analysis, however, when i run the finger print analysis i get below error. RMS analysis is able to split the 
input structure into protein and ligand. Please can I know how I can fix this issue: 

Explicit valence for atom # 301 C, 5, is greater than permitted
Input structure could not be split into protein and ligand. Please check ligand identifier.
Error with fingerprint generation. Please check input files, required packages (specifically ODDT and rdkit builds specified in installation), then try again.
 

Kind Regards,
Chetan

**Comment by justinecwilliams** [comment]
Hi Chetan,

Could you please add your input files, as well as let me know what inputs you are using in the GUI? I'll try this myself and try to debug this for you. Just to check - within the pymol command line are you able to "import oddt" without issue?

Thank you,

Justine

**Comment by poojari1** [comment]
Dear Justine,

Thanks for your quick reply. 

I tested RMS and fingerprint analysis using the examples given in the package and they work fine without any errors.  

"import oddt" loads without errors. 

Since I am using unpublished structure, I wont be able to share the files here. But I can describe my system. Its a dimer 
with chains labelled A and B, separated by TER line, followed by HETATM lines. 
I am using File input-type 2 and use default values for RMS (2.0) and for SPLIF (0.5). 
RMS works fine and creates all the files. Only SPLIF fails. 

I tried to search for this error "Explicit valence for atom # 301 C, 5, is greater than permitted", the posts were linking it posts  from RDkit users such as  "RDKit's valence rules are not allowing me to generate the fingerprint." This is the ligand I am using: https://pubchem.ncbi.nlm.nih.gov/compound/Tecovirimat


Kind Regards,
Chetan

**Comment by poojari1** [comment]
Dear Justine,

I fixed the error. The error was not coming from the ligand but from the protein. 

The protein-ligand complex which was failing came directly from Rosetta. When I used the structure minimized 
from MD simulations everything worked fine. 

Kind Regards,
Chetan
